# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service tin
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/layer: *layer

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  capabilities:
    drop:
      - ALL

# -- Create SecretStore via secret of secrets pattern
sulfoxide-bromine:
  # -- Store name to create
  storeName: doppler-tin
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "SULFOXIDE_TIN"

# -- Cloudflare Tunnel Token
token:

  # -- Secret Name that stores the Token with key CLOUDFLARE_TOKEN
  secretName: &secretName cloudflare-external-dns-token

  # -- Secret directly inlined in value files
  internal:
    # -- Use hard coded secret
    enable: false

    # -- Hard coded Cloudflare token
    token: ""

  # -- Use external secret
  external:

    # -- Enable the use of external secret
    enable: true

    # -- Refresh Rate
    refreshInterval: 1h

    # -- Remote Secret Reference name
    remoteSecretName: MANUAL_CLOUDFLARE_EXTERNAL_DNS_TOKEN

    # Secret Store to reference
    secretStore:
      # -- Name of the Secret Store
      name: doppler-tin

      # -- Kind of the Secret Store: `ClusterSecretStore` or `SecretStore`
      kind: SecretStore

    # -- Secret policy
    policy:
      # -- Creation policy
      creation: Owner

      # -- Deletion policy
      deletion: Retain


# -- ExternalDNS configuration. See [ExternalDNS Helm Chart](https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns)
external-dns:

  interval: 1m
  podSecurityContext:
    <<: *podSecurityContext
  securityContext:
    <<: *securityContext
  podLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
  commonLabels:
    <<: *tags
  deploymentAnnotations:
    <<: *tags
  serviceMonitor:
    enabled: true
  rbac:
    create: true
  logFormat: json
  sources:
    - service
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  provider: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: *secretName
          key: CLOUDFLARE_TOKEN



