{{- if .Values.token.internal.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.token.secretName }}
  annotations: {{- include "sulfoxide-tin.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels: {{- include "sulfoxide-tin.labels" . | nindent 4 }}
data:
  TUNNEL_TOKEN: {{ b64enc .Values.token.internal.token }}
---
{{- end }}
{{- if .Values.token.external.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name -}}-external-secret
  annotations: {{- include "sulfoxide-tin.annotations" . | nindent 4 }}
  labels: {{- include "sulfoxide-tin.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.token.external.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.token.external.secretStore.name }}
    kind: {{ .Values.token.external.secretStore.kind }}
  target:
    name: {{ .Values.token.secretName }}
    creationPolicy: {{ .Values.token.external.policy.creation }}
    deletionPolicy: {{ .Values.token.external.policy.deletion }}
  data:
    - secretKey: CLOUDFLARE_TOKEN
      remoteRef:
        key: "{{ .Values.token.external.remoteSecretName }}"
{{- end }}
